import 'dart:convert';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:image_picker/image_picker.dart';
import 'package:shared_preferences/shared_preferences.dart';

const apiBase='https://YOUR-DOMAIN.example/api';
const demoMode=false; // Set true for offline demo only.

void main()=>runApp(const GarageApp());
class GarageApp extends StatelessWidget{const GarageApp({super.key});@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'Garage Management',theme:ThemeData(useMaterial3:true,colorSchemeSeed:const Color(0xff176b87),scaffoldBackgroundColor:const Color(0xfff4f7fb)),home:const AuthGate());}
class Session{static String? token;static Map<String,dynamic>? user;static Future<void> load()async{final p=await SharedPreferences.getInstance();token=p.getString('token');final s=p.getString('user');if(s!=null)user=jsonDecode(s);}static Future<void> save(String t,Map<String,dynamic> u)async{token=t;user=u;final p=await SharedPreferences.getInstance();await p.setString('token',t);await p.setString('user',jsonEncode(u));}static Future<void> clear()async{token=null;user=null;(await SharedPreferences.getInstance()).clear();}}
class Api{static Future<dynamic> call(String path,{String method='GET',Map<String,dynamic>? body,Map<String,String>? query})async{if(demoMode)return Demo.data(path);var uri=Uri.parse('$apiBase$path').replace(queryParameters:query);final h={'Content-Type':'application/json',if(Session.token!=null)'Authorization':'Bearer ${Session.token}'};late http.Response r;if(method=='POST')r=await http.post(uri,headers:h,body:jsonEncode(body??{}));else if(method=='PATCH')r=await http.patch(uri,headers:h,body:jsonEncode(body??{}));else r=await http.get(uri,headers:h);final d=jsonDecode(r.body);if(r.statusCode>=300)throw Exception(d['error']??'Request failed');return d;}}
class Demo{static dynamic data(String p){if(p=='/vehicles')return {'vehicles':[{'id':1,'registration_no':'KDA 123A','make':'Toyota','model':'Premio','year':2017,'mileage':126400,'customer_name':'Jane Customer'}]};if(p=='/jobs')return {'jobs':[{'id':1,'registration_no':'KDA 123A','make':'Toyota','model':'Premio','customer_name':'Jane Customer','mechanic_name':'John Mechanic','title':'Brake system replacement','status':'in_progress','estimated_cost':'8700'}]};if(p=='/parts')return {'parts':[{'id':1,'sku':'BP-001','name':'Brake Pads','quantity':12,'reorder_level':5,'selling_price':'4500'},{'id':2,'sku':'BF-001','name':'Brake Fluid','quantity':20,'reorder_level':5,'selling_price':'1200'}]};if(p=='/invoices')return {'invoices':[{'id':1,'invoice_no':'INV-20261002-0001','customer_name':'Jane Customer','job_title':'Brake system replacement','total':'8700','paid':'0','status':'unpaid'}]};if(p=='/payments')return {'payments':[]};if(p=='/notifications')return {'notifications':[{'id':1,'title':'Repair started','body':'Your Toyota Premio brake repair is in progress.','created_at':'2026-10-02'}]};return {'customers':1,'mechanics':1,'vehicles':1,'active_jobs':1,'completed_jobs':0,'low_stock':0,'outstanding':'8700','revenue':'0'};}}

class AuthGate extends StatefulWidget{const AuthGate({super.key});@override State<AuthGate> createState()=>_AuthGateState();}
class _AuthGateState extends State<AuthGate>{bool loading=true;@override void initState(){super.initState();Session.load().then((_){setState(()=>loading=false);});}@override Widget build(BuildContext c){if(loading)return const Scaffold(body:Center(child:CircularProgressIndicator()));return Session.user==null?const LoginPage():HomeShell(user:Session.user!);}}
class LoginPage extends StatefulWidget{const LoginPage({super.key});@override State<LoginPage> createState()=>_LoginState();}
class _LoginState extends State<LoginPage>{final e=TextEditingController(text:demoMode?'customer@example.com':'');final p=TextEditingController(text:demoMode?'ChangeMe123!':'');bool busy=false;String? err;Future<void> go()async{setState(()=>busy=true);try{if(demoMode){await Session.save('demo',{'id':3,'name':'Jane Customer','email':'customer@example.com','role':'customer'});}else{final d=await Api.call('/auth/login',method:'POST',body:{'email':e.text.trim(),'password':p.text});await Session.save(d['token'],Map<String,dynamic>.from(d['user']));}if(mounted)Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>HomeShell(user:Session.user!)));}catch(x){setState(()=>err=x.toString());}finally{if(mounted)setState(()=>busy=false);}}@override Widget build(BuildContext c)=>Scaffold(body:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(24),child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:460),child:Card(child:Padding(padding:const EdgeInsets.all(26),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[const Icon(Icons.car_repair,size:70),const SizedBox(height:12),Text('Garage Management',style:Theme.of(c).textTheme.headlineMedium,textAlign:TextAlign.center),const SizedBox(height:22),TextField(controller:e,keyboardType:TextInputType.emailAddress,decoration:const InputDecoration(labelText:'Email',prefixIcon:Icon(Icons.email))),const SizedBox(height:12),TextField(controller:p,obscureText:true,decoration:const InputDecoration(labelText:'Password',prefixIcon:Icon(Icons.lock))),if(err!=null)Padding(padding:const EdgeInsets.only(top:12),child:Text(err!,style:const TextStyle(color:Colors.red))),const SizedBox(height:20),FilledButton(onPressed:busy?null:go,child:Text(busy?'Signing in...':'Sign in')),const SizedBox(height:8),TextButton(onPressed:()=>showDialog(context:context,builder:(_)=>const AlertDialog(title:Text('Registration'),content:Text('Customer registration is available through the API. Ask the garage administrator for an account or enable the registration screen in the next UI iteration.'))),child:const Text('Need an account?'))])))))));}
}
class HomeShell extends StatefulWidget{final Map<String,dynamic> user;const HomeShell({super.key,required this.user});@override State<HomeShell> createState()=>_HomeShellState();}
class _HomeShellState extends State<HomeShell>{int tab=0;@override Widget build(BuildContext c){final role=widget.user['role'];final pages=role=='mechanic'?[const MechanicHome(),const JobsPage(),const PartsPage(),const NotificationsPage()]:[const CustomerHome(),const VehiclesPage(),const InvoicesPage(),const NotificationsPage()];final labels=role=='mechanic'?['Home','Jobs','Parts','Alerts']:['Home','Vehicles','Invoices','Alerts'];return Scaffold(appBar:AppBar(title:Text('${role[0].toUpperCase()}${role.substring(1)} Portal'),actions:[IconButton(onPressed:()async{await Session.clear();if(mounted)Navigator.pushAndRemoveUntil(context,MaterialPageRoute(builder:(_)=>const LoginPage()),(_)=>false);},icon:const Icon(Icons.logout))]),body:pages[tab],bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:[for(final x in labels)NavigationDestination(icon:Icon(_icon(x)),label:x)]));}IconData _icon(String x)=>switch(x){'Home'=>Icons.dashboard,'Jobs'=>Icons.build,'Parts'=>Icons.inventory_2,'Vehicles'=>Icons.directions_car,'Invoices'=>Icons.receipt_long,_=>Icons.notifications};}

class MechanicHome extends StatelessWidget{const MechanicHome({super.key});@override Widget build(BuildContext c)=>FutureBuilder(future:Api.call('/jobs'),builder:(c,s){if(!s.hasData)return const Center(child:CircularProgressIndicator());final jobs=s.data['jobs'];return ListView(padding:const EdgeInsets.all(18),children:[Text('Welcome, ${Session.user?['name']}',style:Theme.of(c).textTheme.headlineSmall),const SizedBox(height:16),StatCard(title:'Assigned jobs',value:'${jobs.length}',icon:Icons.build),const SizedBox(height:12),...jobs.map<Widget>((j)=>JobCard(job:j))]);}}
class CustomerHome extends StatelessWidget{const CustomerHome({super.key});@override Widget build(BuildContext c)=>FutureBuilder(future:Future.wait([Api.call('/vehicles'),Api.call('/jobs'),Api.call('/invoices')]),builder:(c,s){if(!s.hasData)return const Center(child:CircularProgressIndicator());final v=s.data![0]['vehicles'];final j=s.data![1]['jobs'];final i=s.data![2]['invoices'];return ListView(padding:const EdgeInsets.all(18),children:[Text('Hello, ${Session.user?['name']}',style:Theme.of(c).textTheme.headlineSmall),const SizedBox(height:14),Row(children:[Expanded(child:StatCard(title:'Vehicles',value:'${v.length}',icon:Icons.directions_car)),const SizedBox(width:10),Expanded(child:StatCard(title:'Active repairs',value:'${j.length}',icon:Icons.build))]),const SizedBox(height:10),StatCard(title:'Outstanding invoices',value:'${i.length}',icon:Icons.receipt_long),const SizedBox(height:18),const Text('Current repairs',style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)),...j.map<Widget>((x)=>JobCard(job:x))]);}}
class StatCard extends StatelessWidget{final String title,value;final IconData icon;const StatCard({super.key,required this.title,required this.value,required this.icon});@override Widget build(BuildContext c)=>Card(child:Padding(padding:const EdgeInsets.all(16),child:Row(children:[CircleAvatar(child:Icon(icon)),const SizedBox(width:12),Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(color:Colors.grey)),Text(value,style:const TextStyle(fontSize:23,fontWeight:FontWeight.bold))])])));}
class JobCard extends StatelessWidget{final Map<String,dynamic> job;const JobCard({super.key,required this.job});@override Widget build(BuildContext c)=>Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.car_repair)),title:Text(job['title']??'Repair job'),subtitle:Text('${job['registration_no']} • ${job['status']}'),trailing:const Icon(Icons.chevron_right),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>JobDetail(job:job)))));}
class JobsPage extends StatelessWidget{const JobsPage({super.key});@override Widget build(BuildContext c)=>FutureBuilder(future:Api.call('/jobs'),builder:(c,s)=>s.hasData?ListView(padding:const EdgeInsets.all(12),children:[for(final j in s.data['jobs'])JobCard(job:j)]):const Center(child:CircularProgressIndicator()));}
class VehiclesPage extends StatelessWidget{const VehiclesPage({super.key});@override Widget build(BuildContext c)=>FutureBuilder(future:Api.call('/vehicles'),builder:(c,s)=>s.hasData?ListView(padding:const EdgeInsets.all(12),children:[for(final v in s.data['vehicles'])Card(child:ListTile(leading:const Icon(Icons.directions_car),title:Text('${v['make']} ${v['model']??''}'),subtitle:Text('${v['registration_no']} • ${v['mileage']} km')))]):const Center(child:CircularProgressIndicator()));}
class PartsPage extends StatelessWidget{const PartsPage({super.key});@override Widget build(BuildContext c)=>FutureBuilder(future:Api.call('/parts'),builder:(c,s)=>s.hasData?ListView(padding:const EdgeInsets.all(12),children:[for(final p in s.data['parts'])Card(child:ListTile(title:Text(p['name']),subtitle:Text('SKU ${p['sku']}'),trailing:Text('${p['quantity']}')))]):const Center(child:CircularProgressIndicator()));}
class InvoicesPage extends StatelessWidget{const InvoicesPage({super.key});@override Widget build(BuildContext c)=>FutureBuilder(future:Api.call('/invoices'),builder:(c,s)=>s.hasData?ListView(padding:const EdgeInsets.all(12),children:[for(final i in s.data['invoices'])Card(child:ListTile(title:Text(i['invoice_no']),subtitle:Text(i['job_title']),trailing:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Text('KSh ${i['total']}'),TextButton(onPressed:()=>pay(c,i),child:const Text('PAY'))])))]):const Center(child:CircularProgressIndicator()));}
Future<void> pay(BuildContext c,Map i)async{try{await Api.call('/payments/mpesa/stk-push',method:'POST',body:{'invoice_id':i['id'],'phone':Session.user?['phone']});if(c.mounted)ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('M-Pesa prompt requested. Check your phone.')));}catch(e){if(c.mounted)ScaffoldMessenger.of(c).showSnackBar(SnackBar(content:Text(e.toString())));}}
class NotificationsPage extends StatelessWidget{const NotificationsPage({super.key});@override Widget build(BuildContext c)=>FutureBuilder(future:Api.call('/notifications'),builder:(c,s)=>s.hasData?ListView(padding:const EdgeInsets.all(12),children:[for(final n in s.data['notifications'])Card(child:ListTile(leading:const Icon(Icons.notifications),title:Text(n['title']),subtitle:Text(n['body']),trailing:Text(n['created_at'].toString().split(' ').first)))]):const Center(child:CircularProgressIndicator()));}
class JobDetail extends StatefulWidget{final Map<String,dynamic> job;const JobDetail({super.key,required this.job});@override State<JobDetail> createState()=>_JobDetailState();}
class _JobDetailState extends State<JobDetail>{String? status;final notes=TextEditingController();final diagnosis=TextEditingController();final work=TextEditingController();bool busy=false;@override void initState(){super.initState();status=widget.job['status'];}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text('Job #${widget.job['id']}')),body:ListView(padding:const EdgeInsets.all(18),children:[Text('${widget.job['make']} ${widget.job['model']}',style:Theme.of(c).textTheme.headlineSmall),Text(widget.job['registration_no']??''),const SizedBox(height:18),DropdownButtonFormField<String>(value:status,items:['assigned','diagnosing','in_progress','waiting_parts','ready_inspection','completed','cancelled'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>setState(()=>status=v),decoration:const InputDecoration(labelText:'Status')),const SizedBox(height:12),TextField(controller:diagnosis,maxLines:3,decoration:const InputDecoration(labelText:'Diagnosis')),const SizedBox(height:12),TextField(controller:work,maxLines:4,decoration:const InputDecoration(labelText:'Work performed')),const SizedBox(height:12),TextField(controller:notes,maxLines:3,decoration:const InputDecoration(labelText:'Notes')),const SizedBox(height:16),FilledButton.icon(onPressed:busy?null:save,icon:const Icon(Icons.save),label:Text(busy?'Saving...':'Save progress')),const SizedBox(height:8),OutlinedButton.icon(onPressed:pickPhoto,icon:const Icon(Icons.camera_alt),label:const Text('Add repair photo'))]));Future<void> save()async{setState(()=>busy=true);try{await Api.call('/jobs/${widget.job['id']}',method:'PATCH',body:{'status':status,'diagnosis':diagnosis.text,'work_performed':work.text,'notes':notes.text});if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Job updated')));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));}finally{if(mounted)setState(()=>busy=false);}}Future<void> pickPhoto()async{final x=await ImagePicker().pickImage(source:ImageSource.camera,imageQuality:75);if(x==null||demoMode)return;final req=http.MultipartRequest('POST',Uri.parse('$apiBase/jobs/${widget.job['id']}/photos'));req.headers['Authorization']='Bearer ${Session.token}';req.files.add(await http.MultipartFile.fromPath('photo',x.path));final r=await req.send();if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(r.statusCode<300?'Photo uploaded':'Photo upload failed')));}}
