name: garage_management
publish_to: 'none'
version: 2.0.0+2
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
flutter:
  uses-material-design: true
